name: Terraform

defaults:
  run:
    working-directory: ./src/gcp/cloudfunctions

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - src/gcp/cloudfunctions/**

jobs:
  terraform:
    name: Deploy Cloud Functions v2
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/814992956970/locations/global/workloadIdentityPools/zdh-workflow-wi-pool2/providers/github'
        service_account: zdh-workflow-action@bold-seat-291901.iam.gserviceaccount.com

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Zip Function Code
      run: |
        cd manual-input-data-triggerer/
        zip -r function-source.zip *

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan  -var-file=env-vars/${{ github.ref == 'refs/heads/main' && 'prod.tfvars' || 'dev.tfvars' }}

    - name: Terraform Apply
      run: terraform apply -var-file=env-vars/${{ github.ref == 'refs/heads/main' && 'prod.tfvars' || 'dev.tfvars' }} -auto-approve
